GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJZdW1hIE51ciBBbGZhdGgiLCJlbWFpbCI6Inl1bWFudXJhbGZhdGgxQGdtYWlsLmNvbSIsImlhdCI6MTcwNjA1NDAxMiwiZXhwIjoxNzA2MDU0MDcyfQ.aJeuHOgGPDHMzJ32fTiUyxchYYq8J-IT726OUPSeEiI 

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "yumanuralfath1@gmail.com",
  "password": "yumakeren"
}

###
GET http://localhost:8080/token

###
DELETE http://localhost:8080/logout